replace node to hugo

diff --git a/libexec/hugoenv-help b/libexec/hugoenv-help
--- a/libexec/hugoenv-help
+++ b/libexec/hugoenv-help
@@ -2,7 +2,7 @@
 #
 # Summary: Display help for a command
 #
-# Usage: nodenv help [--usage] COMMAND
+# Usage: hugoenv help [--usage] COMMAND
 #
 # Parses and displays help contents from a command's source file.
 #
@@ -13,17 +13,17 @@
 # documentation.
 
 set -e
-[ -n "$NODENV_DEBUG" ] && set -x
+[ -n "$HUGOENV_DEBUG" ] && set -x
 
-# Provide nodenv completions
+# Provide hugoenv completions
 if [ "$1" = "--complete" ]; then
   echo --usage
-  exec nodenv-commands
+  exec hugoenv-commands
 fi
 
 command_path() {
   local command="$1"
-  command -v nodenv-"$command" || command -v nodenv-sh-"$command" || true
+  command -v hugoenv-"$command" || command -v hugoenv-sh-"$command" || true
 }
 
 extract_initial_comment_block() {
@@ -45,7 +45,7 @@ collect_documentation() {
   local awk
   awk="$(type -p gawk awk 2>/dev/null | head -n1)"
   if [ -z "$awk" ]; then
-    echo "nodenv: cannot find awk" >&2
+    echo "hugoenv: cannot find awk" >&2
     return 1
   fi
 
@@ -127,7 +127,7 @@ print_help() {
     if [ -n "$usage" ]; then
       echo "$usage"
     else
-      echo "Usage: nodenv ${command}"
+      echo "Usage: hugoenv ${command}"
     fi
     if [ -n "$help" ]; then
       echo
@@ -153,15 +153,15 @@ if [ "$1" = "--usage" ]; then
   shift
 fi
 
-if [ -z "$1" ] || [ "$1" == "nodenv" ]; then
-  echo "Usage: nodenv <command> [<args>]"
+if [ -z "$1" ] || [ "$1" == "hugoenv" ]; then
+  echo "Usage: hugoenv <command> [<args>]"
   [ -z "$usage" ] || exit
   echo
-  echo "Some useful nodenv commands are:"
+  echo "Some useful hugoenv commands are:"
   print_summaries commands local global shell install uninstall rehash version versions which whence
   echo
-  echo "See \`nodenv help <command>' for information on a specific command."
-  echo "For full documentation, see: https://github.com/nodenv/nodenv#readme"
+  echo "See \`hugoenv help <command>' for information on a specific command."
+  echo "For full documentation, see: https://github.com/hugoenv/hugoenv#readme"
 else
   command="$1"
   if [ -n "$(command_path "$command")" ]; then
@@ -171,7 +171,7 @@ else
       print_help "$command"
     fi
   else
-    echo "nodenv: no such command \`$command'" >&2
+    echo "hugoenv: no such command \`$command'" >&2
     exit 1
   fi
 fi
diff --git a/libexec/hugoenv-hooks b/libexec/hugoenv-hooks
--- a/libexec/hugoenv-hooks
+++ b/libexec/hugoenv-hooks
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Summary: List hook scripts for a given nodenv command
-# Usage: nodenv hooks <command>
+# Summary: List hook scripts for a given hugoenv command
+# Usage: hugoenv hooks <command>
 
 set -e
-[ -n "$NODENV_DEBUG" ] && set -x
+[ -n "$HUGOENV_DEBUG" ] && set -x
 
-# Provide nodenv completions
+# Provide hugoenv completions
 if [ "$1" = "--complete" ]; then
   echo exec
   echo rehash
@@ -15,20 +15,20 @@ if [ "$1" = "--complete" ]; then
   exit
 fi
 
-NODENV_COMMAND="$1"
-if [ -z "$NODENV_COMMAND" ]; then
-  nodenv-help --usage hooks >&2
+HUGOENV_COMMAND="$1"
+if [ -z "$HUGOENV_COMMAND" ]; then
+  hugoenv-help --usage hooks >&2
   exit 1
 fi
 
-if ! enable -f "${BASH_SOURCE%/*}"/nodenv-realpath.dylib realpath 2>/dev/null; then
-  if [ -n "$NODENV_NATIVE_EXT" ]; then
-    echo "nodenv: failed to load \`realpath' builtin" >&2
+if ! enable -f "${BASH_SOURCE%/*}"/hugoenv-realpath.dylib realpath 2>/dev/null; then
+  if [ -n "$HUGOENV_NATIVE_EXT" ]; then
+    echo "hugoenv: failed to load \`realpath' builtin" >&2
     exit 1
   fi
 READLINK=$(type -p greadlink readlink 2>/dev/null | head -n1)
 if [ -z "$READLINK" ]; then
-  echo "nodenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "hugoenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
@@ -52,11 +52,11 @@ realpath() {
 }
 fi
 
-IFS=: hook_paths=($NODENV_HOOK_PATH)
+IFS=: hook_paths=($HUGOENV_HOOK_PATH)
 
 shopt -s nullglob
 for path in "${hook_paths[@]}"; do
-  for script in "$path/$NODENV_COMMAND"/*.bash; do
+  for script in "$path/$HUGOENV_COMMAND"/*.bash; do
     realpath "$script"
   done
 done
diff --git a/libexec/hugoenv-version-file-read b/libexec/hugoenv-version-file-read
--- a/libexec/hugoenv-version-file-read
+++ b/libexec/hugoenv-version-file-read
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
-# Usage: nodenv version-file-read <file>
+# Usage: hugoenv version-file-read <file>
 set -e
-[ -n "$NODENV_DEBUG" ] && set -x
+[ -n "$HUGOENV_DEBUG" ] && set -x
 
 VERSION_FILE="$1"
 
@@ -11,7 +11,7 @@ if [ -s "$VERSION_FILE" ]; then
   read -n 1024 -d "" -r version _ <"$VERSION_FILE" || :
 
   if [[ $version == *..* ]]; then
-    echo "nodenv: invalid version in \`$VERSION_FILE'" >&2
+    echo "hugoenv: invalid version in \`$VERSION_FILE'" >&2
   elif [ -n "$version" ]; then
     echo "$version"
     exit
diff --git a/libexec/hugoenv-versions b/libexec/hugoenv-versions
--- a/libexec/hugoenv-versions
+++ b/libexec/hugoenv-versions
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
-# Summary: List installed Node versions
-# Usage: nodenv versions [--bare] [--skip-aliases]
+# Summary: List installed Hugo versions
+# Usage: hugoenv versions [--bare] [--skip-aliases]
 #
-# Lists all Node versions found in `$NODENV_ROOT/versions/*'.
+# Lists all Hugo versions found in `$HUGOENV_ROOT/versions/*'.
 
 set -e
-[ -n "$NODENV_DEBUG" ] && set -x
+[ -n "$HUGOENV_DEBUG" ] && set -x
 
 unset bare
 unset skip_aliases
-# Provide nodenv completions
+# Provide hugoenv completions
 for arg; do
   case "$arg" in
   --complete )
@@ -19,23 +19,23 @@ for arg; do
   --bare ) bare=1 ;;
   --skip-aliases ) skip_aliases=1 ;;
   * )
-    nodenv-help --usage versions >&2
+    hugoenv-help --usage versions >&2
     exit 1
     ;;
   esac
 done
 
-versions_dir="${NODENV_ROOT}/versions"
+versions_dir="${HUGOENV_ROOT}/versions"
 
-if ! enable -f "${BASH_SOURCE%/*}"/nodenv-realpath.dylib realpath 2>/dev/null; then
-  if [ -n "$NODENV_NATIVE_EXT" ]; then
-    echo "nodenv: failed to load \`realpath' builtin" >&2
+if ! enable -f "${BASH_SOURCE%/*}"/hugoenv-realpath.dylib realpath 2>/dev/null; then
+  if [ -n "$HUGOENV_NATIVE_EXT" ]; then
+    echo "hugoenv: failed to load \`realpath' builtin" >&2
     exit 1
   fi
 
   READLINK=$(type -p greadlink readlink 2>/dev/null | head -n1)
   if [ -z "$READLINK" ]; then
-    echo "nodenv: cannot find readlink - are you missing GNU coreutils?" >&2
+    echo "hugoenv: cannot find readlink - are you missing GNU coreutils?" >&2
     exit 1
   fi
 
@@ -91,21 +91,21 @@ sort_versions() {
 }
 
 versions="$(
-  if NODENV_VERSION=system nodenv-which node >/dev/null 2>&1; then
+  if HUGOENV_VERSION=system hugoenv-which hugo >/dev/null 2>&1; then
     echo system
   fi
   list_versions | sort_versions
 )"
 
 if [ -z "$versions" ]; then
-  echo "Warning: no Node detected on the system" >&2
+  echo "Warning: no Hugo detected on the system" >&2
   exit 1
 fi
 
-current_version="$(nodenv-version-name || true)"
+current_version="$(hugoenv-version-name || true)"
 while read -r version; do
   if [ "$version" == "$current_version" ]; then
-    echo "* $(nodenv-version 2>/dev/null)"
+    echo "* $(hugoenv-version 2>/dev/null)"
   else
     echo "  $version"
   fi
